### ISSUE TITLE
Slider thumbs not keeping their positions when clicked

### ISSUE THREAD

**Issue by mattiagalati** [trikko/vasaro-web#1]
Steps to reproduce:

1. Move the mouse cursor over a slider thumb
2. Click the thumb without moving the mouse and release

The thumb should not move, but instead it slightly slides left

![brave_CstrbZDbYJ](https://user-images.githubusercontent.com/6606297/202925752-a7d22bb1-1cb3-42ab-9bc4-c1e4c8580bb4.gif)

Tried with Brave 1.45.127 (Chromium 107.0.5304.110) on Windows 10

**Comment by trikko** [comment]
Vase profile or noise?

**Comment by trikko** [comment]
Hmm confirmed. If it is over the half it drifts toward the end. @raysan5 is this a known bug in raygui?
